# Generated by Django 4.2.3 on 2023-07-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rForm',
            new_name='userr',
        ),
    ]
