# Generated by Django 3.2.12 on 2024-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_rform_userr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userr',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
