# Generated by Django 5.0.6 on 2024-06-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240607_0912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
