# Generated by Django 5.0.6 on 2024-06-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_register',
        ),
    ]
