# Generated by Django 5.0.6 on 2024-06-12 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_remove_apisfeed_author_remove_hackathonsfeed_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='interested_domains_to_follow',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='followers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='userauth.user_register'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='userauth.user_register'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='skills',
            field=models.CharField(choices=[('python', 'Python'), ('sql', 'SQL'), ('software', 'Software'), ('full stack', 'Full stack developer'), ('front end', 'Front End developer')], default=None, max_length=255),
        ),
    ]
